org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

# Mod Info
mod_version=1.0.0
mod_id=createwarfare
mod_name=Create Warfare
mod_author=Julian
mod_description=
mod_license=MIT

# Group
mod_group_id=com.julian.createwarfare

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

# NeoForge
neo_version=21.1.248
loader_version_range=[4,)

# Parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Create
create_version=6.0.10-280

# Ponder
ponder_version=1.0.82

# Flywheel
flywheel_version=1.0.6

# Registrate
registrate_version=MC1.21-1.3.0+67

# Create Aeronautics
aeronautics_version=44pLdPGg

# Sable
sable_version=2.0.5